var metadata = require('./routes/metadata.js')

Sandbox.define('/metadata/likelihood-to-land/','GET', metadata.likelihoodToLand)
Sandbox.define('/metadata/export-experience-category/','GET', metadata.exportExperienceCategory)
Sandbox.define('/metadata/investment-investor-type/','GET', metadata.investmentInvestorType)
Sandbox.define('/metadata/investment-involvement/','GET', metadata.investmentInvolvement)
Sandbox.define('/metadata/investment-specific-programme/','GET', metadata.investmentSpecificProgramme)
Sandbox.define('/metadata/investment-project-stage/','GET', metadata.investmentProjectStage)
Sandbox.define('/metadata/investment-business-activity/','GET', metadata.investmentBusinessActivity)
Sandbox.define('/metadata/investment-type/','GET', metadata.investmentType)
Sandbox.define('/metadata/investment-strategic-driver/','GET', metadata.investmentStrategicDriver)
Sandbox.define('/metadata/order-service-type/','GET', metadata.orderServiceType)
Sandbox.define('/metadata/order-cancellation-reason/','GET', metadata.orderCancellationReason)
Sandbox.define('/metadata/omis-market/','GET', metadata.omisMarket)
Sandbox.define('/metadata/salary-range/','GET', metadata.salaryRange)
Sandbox.define('/metadata/fdi-value/','GET', metadata.fdiValue)
Sandbox.define('/metadata/fdi-type/','GET', metadata.fdiType)
