version: 2 # Do not upgrade to 2.1 until CircleCI CLI supports it

jobs:
  build:
    docker:
      - image: ukti/data-hub-sandbox
    steps:
      - checkout
      - run:
          name: Start sandbox
          command: java -jar /sandbox.jar --port=8001 --watch=false run
          background: true
      - run:
          name: Install curl
          command: apt-get update && apt-get install -y curl
      - run:
          name: Test if the API is up and running
          command: curl --fail http://localhost:8001/ping.xml

workflows:
  version: 2
  build:
    jobs:
      - build
